add kernel version in bzImage name

diff --git a/build_latest b/build_latest
--- a/build_latest
+++ b/build_latest
@@ -62,18 +62,18 @@ __prep() {
 }
 
 __build() {
-	local target_name="$(basename "$K_CONFIG")-$(date +%s)"
-	[ -e "$K_CONFIG" ] || err "'$K_CONFIG' doesn't exist"
-	[ -e "$GR_DIR/linux-$K_VER/.config" ] &&
-		err "$GR_DIR/linux-$K_VER/.config already exists"
-	cp "$K_CONFIG" $GR_DIR/linux-$K_VER/.config ||
-		err "Couldn't copy '$K_CONFIG' to $GR_DIR/linux-$K_VER/.config"
-	# use make oldnoconfig ; assume the config is for that specific kernel version
-	disp "make oldnoconfig"
-	make -C "$GR_DIR/linux-$K_VER" oldnoconfig || err "make oldnoconfig failed"
-	disp "make"
-	make -C "$GR_DIR/linux-$K_VER" $MAKE_FLAGS || err "'make $MAKE_FLAGS' failed"
-	mkdir -p "$GR_BZIMAGE_DIR"
+	local target_name="$(basename "$K_CONFIG")-$K_VER-$(date +%s)"
+#	[ -e "$K_CONFIG" ] || err "'$K_CONFIG' doesn't exist"
+#	[ -e "$GR_DIR/linux-$K_VER/.config" ] &&
+#		err "$GR_DIR/linux-$K_VER/.config already exists"
+#	cp "$K_CONFIG" $GR_DIR/linux-$K_VER/.config ||
+#		err "Couldn't copy '$K_CONFIG' to $GR_DIR/linux-$K_VER/.config"
+#	# use make oldnoconfig ; assume the config is for that specific kernel version
+#	disp "make oldnoconfig"
+#	make -C "$GR_DIR/linux-$K_VER" oldnoconfig || err "make oldnoconfig failed"
+#	disp "make"
+#	make -C "$GR_DIR/linux-$K_VER" $MAKE_FLAGS || err "'make $MAKE_FLAGS' failed"
+#	mkdir -p "$GR_BZIMAGE_DIR"
 	cp "$GR_DIR/linux-$K_VER/arch/x86/boot/bzImage" "$GR_BZIMAGE_DIR/$target_name" ||
 		err "Couldn't copy $GR_DIR/linux-$K_VER/arch/x86/boot/bzImage to $GR_BZIMAGE_DIR/$target_name"
 	disp "bzImage: $GR_BZIMAGE_DIR/$target_name"
